// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqRu7BSZHgsFcLpIkdEYS0zwrxa71A96U',
    appId: '1:195413448380:web:ab8471fd3237b399dbe2b9',
    messagingSenderId: '195413448380',
    projectId: 'khaled-7de44',
    authDomain: 'khaled-7de44.firebaseapp.com',
    storageBucket: 'khaled-7de44.appspot.com',
    measurementId: 'G-X1M317CDBQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZe0esFaeYuivVRyG-7fbAyY_y0NlfbDY',
    appId: '1:195413448380:android:033a3b9ff290e27edbe2b9',
    messagingSenderId: '195413448380',
    projectId: 'khaled-7de44',
    storageBucket: 'khaled-7de44.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDP4GwDyrEr0N8GONPTIIo1lHdGIg679o',
    appId: '1:195413448380:ios:77ba4ea9cf2363eddbe2b9',
    messagingSenderId: '195413448380',
    projectId: 'khaled-7de44',
    storageBucket: 'khaled-7de44.appspot.com',
    iosBundleId: 'com.example.taskProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDP4GwDyrEr0N8GONPTIIo1lHdGIg679o',
    appId: '1:195413448380:ios:77ba4ea9cf2363eddbe2b9',
    messagingSenderId: '195413448380',
    projectId: 'khaled-7de44',
    storageBucket: 'khaled-7de44.appspot.com',
    iosBundleId: 'com.example.taskProject',
  );
}
